language: python
dist: xenial
sudo: false
script: tox
python:
  - '3.5'
  - '3.6'
  - '3.7'
install:
  - pip install tox-travis tox flake8 coverage codecov
after_success:
  - codecov
services:
  - redis-server
jobs:
  include:
    - stage: deploy
      name: 'PyPI deployment'
      python: '3.7'
      script: skip
      after_success: skip
      services: []
      install: skip
      deploy:
        provider: pypi
        user: jrobichaud
        password:
          secure: UYfQKAmVJvwaZc0jX7ej9DYnNgNK8aQb6rXtWm9WUm6BfvxKdGjWvCJHl/CU2NaAqZV+UAsypQPswoPZX0CiGbKUT/zf8irfs9Ay6/UZjnWGd1PPGi3lPHOJ0zLwKzrsKC1K308BZ1pSdQsbKuOHGATFXKKwDLHfuDA89rQaNOD6cJcAZct1PAQROH6R9OIhHzCXBbZkP8Ak1mic7XQnjiJBWUw/YxRez9gYkNOJjN7QEcJC3HickCfWa5SaHqF3Yss+z9+tXbVHZ9305pVyFbh+QqUtdi9GfDnZEoMac9XyovSxRQwgJAxZH+FBud8tROQFGRR2Qd8AHlkR2f0s6DoF8EBoPRP5GUa89Svlw23o1SVx0jqXQAmhctwL+a5SHed0fhiLC/eYnKT9Qq43VofeD8rLYRvWA8F2Bx3nGeV7YmWzlrqWLNK/p88BfEIQ02dq6ZIbJA3P9lOqWi+E73Tm/f5F+TZcxufFmwPWts2RGDfRng5qEBe8J9eQAR6CmeFG/wRsbchC5QHA9UH6LZVlQmX9Z9sW0HDsbet1ovVDo+j8cMqVbwd3A4XEBHLsO+cJxdWjLuDrrsQAB4k4dVHuosO5SRMN5bxc/Rz/2c3TKdClyfzjW2e38RdABRCmkxU3cS6JOps1qxW7Ky+jth7euE6NTf9nhTuRXV1gKVE=
        on:
          tags: true
