language: python
dist: xenial
sudo: false
script: tox
cache: pip
python:
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'
install: pip install tox-travis tox flake8 coverage codecov
after_success: codecov
services: redis-server
jobs:
  include:
    - name: 'Test demo app'
      python: '3.7'
      install: pip install codecov -r requirements.txt
      env:
        CELERY_BROKER_URL=redis://0.0.0.0:6379
        DJANGO_SETTINGS_MODULE=config.settings.test_demo_app
      script:
        - pytest --cov=./django_structlog_demo_project --cov-append django_structlog_demo_project
    - name: 'Test build doc'
      python: '3.7'
      install: pip install -r requirements/doc.txt
      script:
        - cd docs
        - make html
        - make doctest
      services: []
      after_success: skip
    - stage: linter
      name: 'black'
      python: '3.7'
      install: pip install black
      script: black --check --verbose .
      services: []
      after_success: skip
    - stage: linter
      name: 'flake8'
      python: '3.7'
      install: pip install flake8
      script: flake8
      services: []
      after_success: skip
    - stage: deploy
      name: 'PyPI deployment'
      python: '3.7'
      script: skip
      services: []
      install: skip
      deploy:
        provider: pypi
        user: jrobichaud
        password:
          secure: SiwyPhGfzc/ztfrZfse7NGp2vELyqqpkuGQkyZGcyg+WD5Umyl5PhSUY8yowKOrz2mM5x4yXRD+doXnPVpYfTvhHLNzCOOqGCBSNM2VFm/5KP17YbKwSUIxXi67cEIZjD04nMFQwaA2zADmleA1e3/pqQSZr2juEt1XttttZx9O2PsgwOZ1adeeN65j/nPf5LX3sd51NfcYI+dkv6Bhd5ATl5mZ/rbjtBQ/XA80jCA1fYPpLh8rv0KVMnhfcTN0+ukbqzcirjjU1q362pdbY80NxHuQfXoX/3tr/U4Aym64hyZsLMbmLZAlxHh9F8c9ohcmCeeS9ywRFPWiZ4am2UAV4WVanWEERrylsnIWHuTW6FXVwKbgk5DP5xcGZjXnh5SS2KHK7V1BSKKRyaS1s6XILlUtphe5SZoM+b5hksYoio/Xzg174kDSD9M9pMb0WMohyxQVRAgBi9QldSP6jkj/oMZYKDU7goaL8qD22ZsXFjzUBkxbHdtrmzSsh0CerKv1IoBCrVUDob8zvXArbOB58qbs6bKhD62hrriDSJGTcz6LYuzBSgX+cPnfJ2wisIFKoOMGUlbGx2f40O7vuxzbCRKff/6SP0MBwneARNP7MsR79fD/YTASu4a8GT2X6sn2KlmQt6mt0KZ4Yoa5u2PTwK9lp7DvbXihuIuRrOHA=
        on:
          tags: true
        distributions: "sdist bdist_wheel"
